### ISSUE TITLE
image.contents are of type string - needs to be Buffer, Stream, null

### ISSUE THREAD

**Issue by anoff** [eshepelyuk/asciidoctor-plantuml.js#54]
Running the latest example of your [asciidoctor-plantuml-antora]() example I am getting the following error.

```text
▶git log | head -n3
commit c4d41354e07eb5e7ee43d36263edd413230d8289
Author: Ievgenii Shepeliuk <eshepelyuk@newagesol.com>
Date:   Sun Mar 17 21:18:03 2019 +0200

21:51:07 in asciidoctor-plantuml-antora on  master is 📦 ⚠ via ⬢ v11.3.0 
▶antora site.yml --stacktrace
Error: File.contents can only be a Buffer, a Stream, or null.
    at File.set (/usr/local/lib/node_modules/@antora/site-generator-default/node_modules/vinyl/index.js:182:13)
    at new File (/usr/local/lib/node_modules/@antora/site-generator-default/node_modules/vinyl/index.js:34:17)
    at new File (/usr/local/lib/node_modules/@antora/site-generator-default/node_modules/@antora/content-classifier/lib/file.js:5:1)
    at ContentCatalog.addFile (/usr/local/lib/node_modules/@antora/site-generator-default/node_modules/@antora/content-classifier/lib/content-catalog.js:93:37)
    at add (/developer/anoff/asciidoctor-plantuml-antora/node_modules/asciidoctor-plantuml/dist/node/asciidoctor-plantuml.js:145:20)
    at Object.module.exports.save (/developer/anoff/asciidoctor-plantuml-antora/node_modules/asciidoctor-plantuml/dist/node/fetch.js:20:3)
    at createImageSrc (/developer/anoff/asciidoctor-plantuml-antora/node_modules/asciidoctor-plantuml/dist/node/asciidoctor-plantuml.js:37:37)
    at processPlantuml (/developer/anoff/asciidoctor-plantuml-antora/node_modules/asciidoctor-plantuml/dist/node/asciidoctor-plantuml.js:67:24)
    at self.process (/developer/anoff/asciidoctor-plantuml-antora/node_modules/asciidoctor-plantuml/dist/node/asciidoctor-plantuml.js:98:16)
    at Object.apply (/usr/local/lib/node_modules/@antora/site-generator-default/node_modules/asciidoctor.js/dist/node/asciidoctor.js:22093:21)
```

Checking the arguments being passed to the antora adapter the `image.contents` are of type string.

**Comment by eshepelyuk** [comment]
Fixed in https://github.com/eshepelyuk/asciidoctor-plantuml.js/releases/tag/1.1.13
