### ISSUE TITLE
Release 1.3.0 makes Antora crash

### ISSUE THREAD

**Issue by akosma** [eshepelyuk/asciidoctor-plantuml.js#61]
I've updated an Antora site to use version 1.3.0 and the `antora` command fails with the following stacktrace:

```
TypeError: Cannot convert undefined or null to object
    at hasOwnProperty (<anonymous>)
    at Object.Opal.hash_get (/usr/local/share/.config/yarn/global/node_modules/opal-runtime/src/opal.js:1948:19)
    at process (/usr/local/share/.config/yarn/global/node_modules/asciidoctor-plantuml/dist/node/asciidoctor-plantuml.js:27:23)
    at Object.apply (/usr/local/share/.config/yarn/global/node_modules/asciidoctor.js/dist/node/asciidoctor.js:22093:21)
    at Object.Opal.yieldX (/usr/local/share/.config/yarn/global/node_modules/opal-runtime/src/opal.js:1464:18)
    at Proxy.$$call (/usr/local/share/.config/yarn/global/node_modules/opal-runtime/src/opal.js:18246:25)
    at Opal.send (/usr/local/share/.config/yarn/global/node_modules/opal-runtime/src/opal.js:1660:19)
    at $BlockProcessor.$$process (/usr/local/share/.config/yarn/global/node_modules/asciidoctor.js/dist/node/asciidoctor.js:17631:20)
    at $Method.$$call (/usr/local/share/.config/yarn/global/node_modules/opal-runtime/src/opal.js:18459:26)
    at Object.Opal.send (/usr/local/share/.config/yarn/global/node_modules/opal-runtime/src/opal.js:1660:19)
```

The same project (Antora site with just one PlantUML diagram) works perfectly well with version 1.1.13. Haven't tested with 1.2.0.

**Comment by akosma** [comment]
I've just tried to do the same with the [Antora demo site for this plugin](https://github.com/eshepelyuk/asciidoctor-plantuml-antora) and had exactly the same error.

**Comment by niborb** [comment]
I also encounter the same issue unfortunately with the new update.

**Comment by niborb** [comment]
Actually the problem is introduced with v1.2.0. 
v1.1.13 is working fine for me.

**Comment by eshepelyuk** [comment]
Already working on this. Still no clue what's going on.

**Comment by eshepelyuk** [comment]
Hello, 

Just released 1.3.1 and updated [demo site](https://github.com/eshepelyuk/asciidoctor-plantuml-antora)
works for me, could you try it yourself ?

**Comment by akosma** [comment]
Works for me! Thanks a lot

**Comment by eshepelyuk** [comment]
@niborb can you plz check ?
